### PR TITLE
Linux 4.14.310 + 4.14.311 + 4.14.312 + 4.14.313

### PR DESCRIPTION
**Pull request by InitFlo**

### CODE REVIEW

**Comment by SonalSingh18** [comment]
did u tested it by compiling?

**Comment by InitFlo** [comment]
Yes, I did. The build completed sucessfully in ~ 9 minutes on my vm.
The reason why I disabled the upload in the build shell script is that I had a few tries to solve some minor merge conflicts.

**Comment by SonalSingh18** [comment]
> Yes, I did. The build completed sucessfully in ~ 9 minutes on my vm. The reason why I disabled the upload in the build shell script is that I had a few tries to solve some minor merge conflicts.

Tried by flashing kernel?

**Comment by InitFlo** [comment]
> > Yes, I did. The build completed sucessfully in ~ 9 minutes on my vm. The reason why I disabled the upload in the build shell script is that I had a few tries to solve some minor merge conflicts.
> 
> Tried by flashing kernel?

I'm currently using the custom evolution x rom built by you, which sadly bootloops with flashing any newer kernel than the included 4.14.307. The anchor that rescued my joyeuse (which is used as a daliy driver) was reflashing the rom.

When I have some spare time, I'm willing to try to update to the april (or the coming may) security patch. Compiling a rom on my vm steroids with 12 threads, ~ 12 GB ram, ~ 20 GB swap takes at least 3 hours...

**Pull request merged**
