### PR TITLE
Fixed some regressions

### PR DESCRIPTION
**Pull request by InitFlo**
Luckily I had a backup und tested it.

### CODE REVIEW

**Review by SonalSingh18 — COMMENTED** [review]
ak3 as a git submodule isnt buildable on my end

**Comment by InitFlo** [comment]
Did you execute `git submodule update`?
If it fails, delete the AnyKernel folder und update the submodule again.

**Comment by SonalSingh18** [comment]
> Did you execute `git submodule update`? If it fails, delete the AnyKernel folder und update the submodule again.

i just cloned nd tried building by executing build.sh

**Comment by InitFlo** [comment]
Then the folder was empty until the submodule was updated.
I apologize for the inconvience with the previous pull request. By accient caused by disruption the banner and miatoll specific customization in AnyKernel were lost. Do you know this meme: https://9gag.com/gag/an5X26o?🤣

**Comment by InitFlo** [comment]
New Kernel and AnyKernel3 update. Flashed successfully.

**Comment by InitFlo** [comment]
Kernel v4.14.322 + another AnyKernel3 update. Compiled and flashed sucessfully.

**Comment by SonalSingh-nxg** [comment]
share kernel zip with me in pm

**Comment by InitFlo** [comment]
https://drive.google.com/file/d/14LcskxWWLlB3Ue3c7hCDFvieqhms76MC/view?usp=drivesdk <-- 4.14.322
https://drive.google.com/file/d/1523bd4tFYFA7YFIA7P8o62eDMoqaqKPR/view?usp=drivesdk <-- 4.14.323

**Comment by InitFlo** [comment]
Hey,
I solved the merge confilcts.

**Comment by SonalSingh18** [comment]
make a new PR if you could

**Pull request closed without merging**
