### PR TITLE
update to python3 and update AnyKernel3

### PR DESCRIPTION
**Pull request by InitFlo**
Updating AnyKernel3 also fixes the bootloops in evolutionx caused by flashing the new kernel in ofox.

### CODE REVIEW

**Comment by ghost** [comment]
is it tested? last time i merged 4.14.315 nd 316, it bootloops

**Comment by InitFlo** [comment]
Yes, the sources compiled without errors. Then I flashed it successfully onto the official rom by using ofox. No bootloop.
Screenshot_20230608-065815_Einstellungen

**Comment by InitFlo** [comment]
Updated to 4.14.317, my joyeuse runs great.

**Review by ghost — APPROVED** [review]

**Comment by InitFlo** [comment]
And 4.14.318 was released, so I merged it too. I tested it by compiling and flashing, of course.

**Comment by InitFlo** [comment]
4.14.319 is also fine.

**Comment by InitFlo** [comment]
Thx for merging. A custom build with latest evox 7.9.3 runs smooth as butter.

**Pull request merged**
